version: '3.7'

services:
    api:
        build: ./corona/backend/
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 7000
        volumes:
            - ./corona/backend/:/usr/src/corona
        ports:
            - 7000:7000
        image: corona_api:latest
    app:
        build: ./corona/frontend
        command: streamlit run app/main.py --server.port 8501
        volumes:
            - ./corona/frontend/:/usr/src/streamlit
        ports:
            - 8501:8501
        image: corona_app:latest
